version: '3'

services:

  web:
    image: jrouly/employability-web:latest
    container_name: employability-web
    ports: ["127.0.0.1:9000:9000"]
    environment:
      - EMPLOYABILITY_APP_SECRET
      - ELASTICSEARCH_URL=http://employability-elasticsearch:9200

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.3.2
    container_name: employability-elasticsearch
    expose: ["9200", "9300"]
    environment:
      - discovery.type=single-node
      - cluster.name=employability
      - path.repo=/usr/share/elasticsearch/backups
    volumes:
      - "data-elasticsearch:/usr/share/elasticsearch/data"

  postgres:
    image: postgres:10
    container_name: employability-postgres
    expose: ["5432"]
    environment:
      POSTGRES_USER: employability
      POSTGRES_PASSWORD: employability
    volumes:
      - "data-postgres:/var/lib/postgresql"

  kibana:
    image: docker.elastic.co/kibana/kibana:6.3.2
    container_name: employability-kibana
    ports: ["127.0.0.1:5601:5601"]
    environment:
      - xpack.monitoring.enabled=true
      - server.name=employability

volumes:
  data-elasticsearch:
  data-postgres:
